version: '3.2'
services:
    bulk:
        build:
            context: ..
        image: letarette
        volumes:
            - type: bind
              source: ../../wpslurp
              target: /wp
        entrypoint: ["./lrcli", "load", "-a", "-l", "10000", "docs", "/wp/1M.json.gz"]
        environment:
            LETARETTE_DB_PATH: /db/letarette.db
volumes:
    dbvolume: {}
