version: '3.2'
services:
    natsserver:
        image: nats:2-scratch
    letarette:
        build:
            context: ..
        image: letarette
        depends_on:
            - natsserver
        volumes: 
            - dbvolume:/db
    docserver:
        image: letarette
        depends_on:
            - natsserver
            - letarette
        volumes:
            - type: bind
              source: ../testdata
              target: /data
        entrypoint: ["./tinysrv", "-n", "nats://natsserver:4222", "-l", "10000", "docs", "/data/1M.json.gz"]
    monitor:
        image: letarette
        depends_on:
            - natsserver
            - letarette
        environment:
            LRMON_NATS_URLS: nats://natsserver:4222
        entrypoint: ["./lrcli", "monitor"]
volumes:
    dbvolume: {}
