name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
        
    - name: Install go-bindata
      run: go get -u github.com/go-bindata/go-bindata/...

    - name: Install sqlite3
      run: sudo apt-get install -y libsqlite3-dev
      if: startsWith(matrix.os, 'ubuntu')

    - name: Install sqlite3
      run: brew install libsqlite3-dev
      if: startsWith(matrix.os, 'macos')

    - name: Build
      run: make
    
    - name: Test
      run: make test
