name: Master build

on:
  push:
    branches:
      - releasescript

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: setup
    env:
      TAG:  ${{ jobs.setup.steps.tag.outputs.tag }}
      ARCHIVE: ${{ format('letarette-{0}.zip', jobs.setup.steps.tag.outputs.tag) }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Fake assets
        run: touch linux macos
      - name: Pack release
        id: pack-release
        run: zip -r $ARCHIVE linux macos

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: true
      
      - name: Upload release assets
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $ARCHIVE
          asset_name: $ARCHIVE
          asset_content_type: application/zip
