name: Develop branch build

on:
  push:
    branches:
      - develop

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Get GOCACHE
      run: go run bygg/bygg.go gocache
    
    - name: Cache go build cache
      uses: actions/cache@v1
      with:
        path: ${{ env.GOCACHE }}
        key: ${{ runner.os }}-gocache-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-gocache-

    - name: Init submodule
      run: git submodule init && git submodule update --recursive

    - name: Get libstemmer version
      run: git submodule status internal/snowball/snowball > snowball.status

    - name: Cache libstemmer
      uses: actions/cache@v1
      with:
        path: internal/snowball/snowball
        key: ${{ runner.os }}-snowball-${{ hashFiles('snowball.status') }}
        restore-keys: ${{ runner.os }}-snowball-

    - name: Build
      run: go run bygg/bygg.go

    - name: Test
      run: go run bygg/bygg.go test

    - name: Test-build Docker image
      if: startsWith(matrix.os, 'ubuntu')
      run: docker build .

    - name: Collect licenses
      if: startsWith(matrix.os, 'ubuntu')
      run: ./licenses.sh

    - name: Save license info
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v1
      with:
        name: licenses
        path: licenses

    - name: Save change log
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/upload-artifact@v1
      with:
        name: changelog
        path: CHANGELOG.md

    - name: Save artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ format('letarette-{0}', matrix.os) }}
        path: letarette
