name: Docker build and push

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_SECRET }}

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set TAG
        run: echo TAG=${GITHUB_REF:10} >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t letarette/letarette:$TAG .

      - name: Push docker image
        run: |
          docker login -u letarette -p "${DOCKER_TOKEN}"
          docker push letarette/letarette:$TAG
